import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import { Inter } from 'next/font/google';

export const metadata: Metadata = {
  title: 'LocalPoint',
  description: 'Generated by create next app',
};
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={inter.className}>
      <head></head>
      <body className="antialiased" style={{ fontFamily: 'Inter Tight, sans-serif' }}>
        <Toaster position="top-right" />
        {children}
      </body>
    </html>
  );
}
